name: Evaluacion NoSQL

on: [push]

jobs:
  evaluar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Ejecutar evaluaci√≥n
        env:
          ALUMNOS_GRUPOS: ${{ secrets.ALUMNOS_GRUPOS }}
          RESPUESTAS_CORRECTAS: ${{ secrets.RESPUESTAS_CORRECTAS }}
        run: |
          python scripts/evaluar.py ${{ github.actor }}
